from pydantic import BaseModel, Field
from typing import List, Literal, Annotated, Optional

class Section(BaseModel):
    start_line: int = Field(description="Line number where this topic starts")
    topic: str = Field(description="Short name for the topic")
    parent: Optional[str] = Field(default=None, description="Parent topic name, or null")

class Sections(BaseModel):
    sections: List[Section]

class GeneratedQuestion(BaseModel):
    question: str = Field(description="The question generated by the llm")
    ideal_answer: str = Field(description="A correct answer")
    key_points: List[str] = Field(description="2-4 key ideas of correct answer")
    difficulty: int = Field(ge=1, le=5)

class GeneratedQuestions(BaseModel):
    questions: List[GeneratedQuestion] = Field(description="10 to 15 questions spread across difficulty levels 1-5")

class Question(BaseModel):
    """A question as it comes back OUT of the database.

    Distinct from GeneratedQuestion, which is what the LLM produces: this has
    the db-assigned question_id, the topic/parent attached at insert time, and
    uses the column name question_text rather than the schema's `question`.
    """
    question_id: int
    question_text: str
    ideal_answer: str
    key_points: List[str]
    difficulty: int = Field(ge=1, le=5)
    topic: str
    parent: Optional[str] = None

class GradeVerdict(BaseModel):
    verdict: Literal['correct', 'partial', 'wrong', 'dont_know', 'unclear']
    matched_points: List[str] = Field(default_factory=list)
    missed_points: List[str] = Field(default_factory=list)
    confidence: float = Field(ge=0.0, le=1.0)
    reasoning: str

    class Config:
        extra = 'forbid'
        anystr_strip_whitespace = True

